### PR TITLE
Added tests for scrolling behavior

### PR DESCRIPTION
**Pull request by idcuesta**
I have changed:
- Changed iOS Deployment target from iOS6 to iOS7, mainly because of warning in some iOS7+ collectionView methods
- Changed rootViewController of main window to be a tabBar controller, keeping the existing controller as the first tab, and adding a second tab with a collectionViewController
- Added some tests that demonstrate how scrolling should work

<h4>Note</h4>
Most of the test added will fail with existing version of calabash, because of the scrolling behavior, but should pass once the calabash framework is updated to the version that includes this PR -> https://github.com/calabash/calabash-ios-server/pull/120

### CODE REVIEW

**Comment by jmoody** [comment]
@idcuesta Can you make me a collaborator on your project?

I am not sure I will merge this into chou.  This app is meant to be a very tiny app.

I will, however, evaluate this PR and will use your changes to evaluate the  https://github.com/calabash/calabash-ios-server/pull/120.

Where can I send your ice cream?

**Comment by idcuesta** [comment]
I have added you as collaborator :)

**Comment by jmoody** [comment]
Wow.  These are great cukes!

**Comment by jmoody** [comment]
I am going to merge these changes into animated happiness for the time being.  I think that it is worth running these cukes until we can migrate them Briar iOS Example.

**Pull request merged**
